server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: 'application/json,text/plain,text/html'

spring:
  application:
    name: scale-mall
  main:
    web-application-type: reactive
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  codec:
    max-in-memory-size: 20MB
  webflux:
    cors:
      mappings:
        - path-pattern: '/**'
          allowed-origins: '*'
          allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS'
          allowed-headers: '*'
          allow-credentials: false
          max-age: 3600

  data:
    redis:
      client-type: lettuce
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2s
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:200}
          max-idle: ${REDIS_POOL_MAX_IDLE:50}
          min-idle: ${REDIS_POOL_MIN_IDLE:10}
          max-wait: 2s

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics,prometheus'
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    reactor.netty: INFO
    io.lettuce.core: WARN
  file:
    name: ${LOG_FILE:logs/scale-mall.log}
