spring:
  application:
    name: scalemall

  main:
    web-application-type: reactive
    webflux:
      base-path: /

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
